# Generated by Django 4.2.6 on 2025-03-09 04:12

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=imagekit.models.fields.ProcessedImageField(upload_to='photos/%Y/%m/'),
        ),
    ]
